version: "3.8"

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=streaming-io
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
